#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-measures
Version  : 0.2
Release  : 3
URL      : https://cran.r-project.org/src/contrib/measures_0.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/measures_0.2.tar.gz
Summary  : Performance Measures for Statistical Learning
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-R

%description
# measures
Package that provides the biggest amount of statistical measures in the whole R world!

%prep
%setup -q -c -n measures

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533751528

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1533751528
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library measures
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library measures
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library measures
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library measures|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/measures/DESCRIPTION
/usr/lib64/R/library/measures/INDEX
/usr/lib64/R/library/measures/Meta/Rd.rds
/usr/lib64/R/library/measures/Meta/features.rds
/usr/lib64/R/library/measures/Meta/hsearch.rds
/usr/lib64/R/library/measures/Meta/links.rds
/usr/lib64/R/library/measures/Meta/nsInfo.rds
/usr/lib64/R/library/measures/Meta/package.rds
/usr/lib64/R/library/measures/NAMESPACE
/usr/lib64/R/library/measures/R/measures
/usr/lib64/R/library/measures/R/measures.rdb
/usr/lib64/R/library/measures/R/measures.rdx
/usr/lib64/R/library/measures/R/sysdata.rdb
/usr/lib64/R/library/measures/R/sysdata.rdx
/usr/lib64/R/library/measures/help/AnIndex
/usr/lib64/R/library/measures/help/aliases.rds
/usr/lib64/R/library/measures/help/measures.rdb
/usr/lib64/R/library/measures/help/measures.rdx
/usr/lib64/R/library/measures/help/paths.rds
/usr/lib64/R/library/measures/html/00Index.html
/usr/lib64/R/library/measures/html/R.css
